// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://torjueytqlcflovdswbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcmp1ZXl0cWxjZmxvdmRzd2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODU0OTksImV4cCI6MjA1Njc2MTQ5OX0.QNm7JWiCb9g_xB6kxygn86bWhj4HUU39XO_QTpPZTr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);